// <auto-generated />
namespace Steganografia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Session_IsActiveColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Session_IsActiveColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201704102150195_Session_IsActiveColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
